version: '3.1'
services:
  stats-server:
    build: stats-server
    image: stats-server
    container_name: stats_server_container
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsServer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=9090


  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "5500:5432"
    environment:
      - POSTGRES_DB=statsServer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    container_name: ewm_service_container
    build: ewm-service
    image: ewm-service
    depends_on:
      - stats-db
      - ewm-db
    ports:
      - "8080:8080"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmService
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - EXPLORE_WITH_ME_STATS_SERVICE_URL=http://stats-server:9090


  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db
    ports:
      - "5600:5432"
    environment:
      - POSTGRES_DB=ewmService
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres



