CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(250)                            NOT NULL,
    uri       VARCHAR(2000)                           NOT NULL,
    ip        VARCHAR(255)                            NOT NULL,
    timestamp TIMESTAMP without time zone             NOT NULL,
    CONSTRAINT PK_HITS PRIMARY KEY (id)
);
